defmodule ShhAi.Audit.EventRecord do
  @moduledoc """
  Ecto schema for the `events` audit table.

  Each row represents one request metrics event persisted when
  Audit Mode is ON. The `pii_types`, `timings`, and `error` columns
  are JSON-encoded TEXT (the Writer encodes with `Jason.encode!/1`
  before insertion; readers decode with `Jason.decode!/1`).

  Event IDs are application-generated UUIDs (not autogenerated by
  SQLite). `started_at` and `ended_at` are converted from the
  `ShhAi.Metrics.Event` microsecond integers at the Writer seam.

  See ADR 0010 / issue #25.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :string, autogenerate: false}

  schema "events" do
    field(:started_at, :naive_datetime)
    field(:ended_at, :naive_datetime)
    field(:duration_ms, :float)
    field(:source_provider, :string)
    field(:target_provider, :string)
    field(:request_path, :string)
    field(:method, :string)
    field(:streaming, :boolean, default: false)
    field(:status, :integer)
    field(:conversation_id, :string)
    field(:pii_detected_count, :integer)
    field(:pii_sanitized_count, :integer)
    field(:pii_preserved_count, :integer)
    field(:pii_types, :string)
    field(:timings, :string)
    field(:error, :string)
    field(:inserted_at, :naive_datetime)
  end

  @required [
    :id,
    :started_at,
    :ended_at,
    :duration_ms,
    :source_provider,
    :target_provider,
    :streaming,
    :pii_detected_count,
    :pii_sanitized_count,
    :pii_preserved_count,
    :pii_types,
    :timings,
    :inserted_at
  ]

  @doc """
  Changeset for inserting a new event row.
  """
  def changeset(event, attrs) do
    event
    |> cast(attrs, @required ++ [:request_path, :method, :status, :conversation_id, :error])
    |> validate_required(@required)
  end
end
